# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='home_work',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.HomeWork'),
        ),
    ]
