# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20160711_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='dialog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.Dialog'),
        ),
    ]
